ex:
  EXCHANGE_NAME: spring_rb_exchange
  QUEUE_NAME: spring_rb_queue
  ROUNTING_KEY: spring
  IP_ADDRESS: ycrabbitmq.dc.zz
queue:
  QUEUE_NAME: spring_rb_queue
  ROUNTING_KEY: spring
spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: yunce
    publisher-returns: true
    publisher-confirms: true
    template:
      mandatory: true
    host: ycrabbitmq.dc.zz
logging:
  file: /logs/log.log
