ex:
  EXCHANGE_NAME: spring_rb_exchange
  QUEUE_NAME: spring_rb_queue
  ROUNTING_KEY: spring
  #  IP_ADDRESS: ycrabbitmq.dc.zz
  IP_ADDRESS: localhost
queue:
  QUEUE_NAME: spring_rb_queue
  ROUNTING_KEY: spring
spring:
  rabbitmq:
    username: admin
    password: admin
    #    virtual-host: yunce
    virtual-host: /
    #    host: ycrabbitmq.dc.zz
    host: localhost
logging:
  file: /logs/log.log
