ex:
  EXCHANGE_NAME: spring_rb_exchange
  QUEUE_NAME: spring_rb_queue
  ROUNTING_KEY: spring
  #  IP_ADDRESS: ycrabbitmq.dc.zz
  IP_ADDRESS: localhost
queue:
  QUEUE_NAME: spring_rb_queue
  ROUNTING_KEY: spring
spring:
  rabbitmq:
    username: admin
    password: admin
    #    virtual-host: yunce
    virtual-host: /
    #    host: ycrabbitmq.dc.zz
    host: localhost
    publisher-confirms: true
    publisher-returns: true
  application:
    name: rabbitdemo
logging:
  file: logs/log.log
  level.root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{10} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{10} - %msg%n'
server:
  port: 8066